'use client';
import {useEffect,useRef,useState} from 'react';
import {api,Job} from '@/lib/api';
import {Loader2,Mic} from 'lucide-react';
type Question={id:string;question:string;category:string;stage:string;difficulty:string;role_families:string[];topics:string[];evaluation_criteria:string[];answer_guidance:string;follow_ups:string[];match_reason:string;provenance:string;sources:{id:string;title:string;url:string;status:string}[]};
type Feedback={score:number;strengths:string[];missing_elements:string[];improved_answer_suggestion:string};
type Catalog={total:number;role_families:string[];categories:string[];stages:string[];sources:Question['sources']};
export default function InterviewCoach({jobs,initialJob='',localAI=false}:{jobs:Job[];initialJob?:string;localAI?:boolean}){
 const [job,setJob]=useState(initialJob),[catalog,setCatalog]=useState<Catalog|null>(null),[questions,setQuestions]=useState<Question[]>([]),[role,setRole]=useState(''),[category,setCategory]=useState(''),[stage,setStage]=useState(''),[search,setSearch]=useState(''),[active,setActive]=useState(''),[drafts,setDrafts]=useState<Record<string,string>>({}),[reviews,setReviews]=useState<Record<string,Feedback>>({}),[loading,setLoading]=useState(false),[evaluating,setEvaluating]=useState(false),[error,setError]=useState('');
 const request=useRef(0),evaluation=useRef(0);
 useEffect(()=>{let alive=true;api<Catalog>('/interview/catalog').then(c=>{if(alive)setCatalog(c)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[]);
 useEffect(()=>{const n=++request.current;setLoading(true);setError('');const params=new URLSearchParams();if(job)params.set('job_id',job);
 api<Question[]>(`/interview/questions?${params}`).then(q=>{if(n===request.current){setQuestions(q);setActive(q[0]?.id||'')}}).catch(e=>{if(n===request.current)setError(e.message)}).finally(()=>{if(n===request.current)setLoading(false)});return()=>{request.current++;evaluation.current++}},[job]);
 const visible=questions.filter(q=>(!role||q.role_families.includes(role))&&(!category||q.category===category)&&(!stage||q.stage===stage)&&`${q.question} ${q.role_families.join(' ')} ${q.topics.join(' ')} ${q.category}`.toLowerCase().includes(search.toLowerCase()));
 const current=visible.find(q=>q.id===active)||visible[0],index=current?visible.indexOf(current):0,key=`${job||'library'}:${current?.id}`,answer=drafts[key]||'',feedback=reviews[key];
 async function evaluate(){if(!current)return;const token=++evaluation.current;setEvaluating(true);setError('');try{const result=await api<Feedback>('/interview/evaluate','POST',{job_id:job||null,question_id:current.id,answer});if(token===evaluation.current)setReviews(old=>({...old,[key]:result}))}catch(e){if(token===evaluation.current)setError(e instanceof Error?e.message:'Feedback failed.')}finally{setEvaluating(false)}}
 return <div className="interview-workspace"><div className="coach-layout"><section className="coach-setup"><span className="document-icon"><Mic size={25}/></span><h2>Your practice room</h2><p>{catalog?.total||'…'} questions · Explore the library or prepare for a saved opportunity.</p>
 <label>Practice for<select aria-label="Practice for" disabled={evaluating} value={job} onChange={e=>{setJob(e.target.value);setRole('')}}><option value="">All questions · no job required</option>{jobs.map(j=><option key={j.job_id} value={j.job_id}>{j.company_name} · {j.job_title}</option>)}</select></label>
 <label>Search questions<input value={search} disabled={evaluating} onChange={e=>setSearch(e.target.value)} placeholder="Try SQL, feedback, compensation…"/></label>
 <label>Role family<select aria-label="Role family" value={role} disabled={evaluating} onChange={e=>setRole(e.target.value)}><option value="">All available families</option>{catalog?.role_families.map(r=><option key={r}>{r}</option>)}</select></label>
 <label>Category<select aria-label="Category" value={category} disabled={evaluating} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{catalog?.categories.map(c=><option key={c}>{c}</option>)}</select></label>
 <label>Interview stage<select aria-label="Interview stage" value={stage} disabled={evaluating} onChange={e=>setStage(e.target.value)}><option value="">All stages</option>{catalog?.stages.map(s=><option key={s}>{s}</option>)}</select></label>
 <p className="muted">Original practice prompts, not predictions of an employer's questions. Answers remain in this practice view and are sent to the server when you request feedback. Leaving this view clears drafts.</p>
 </section><section className="coach-session">{error&&<div className="error-banner" role="alert">{error}</div>}{loading?<p role="status"><Loader2 className="spin" size={18}/> Loading questions…</p>:current?<><div className="section-title"><span className="tiny-pill">{current.category} · {current.difficulty}</span><small>{index+1} of {visible.length}</small></div><p className="muted">{current.stage} · {current.match_reason}</p><h2>{current.question}</h2><div className="criteria">{current.evaluation_criteria.map(c=><span key={c}>{c}</span>)}</div><details className="interview-guidance"><summary>Answer framework & follow-up</summary><p>{current.answer_guidance}</p>{current.follow_ups.map(f=><p key={f}><strong>Follow-up:</strong> {f}</p>)}<p>Use your own experience. Do not invent achievements or metrics.</p></details>
 <label htmlFor="practice-answer">Your answer</label><textarea id="practice-answer" rows={8} maxLength={20000} disabled={evaluating} value={answer} placeholder="Explain your reasoning or use a real example…" onChange={e=>{setDrafts(d=>({...d,[key]:e.target.value}));setReviews(r=>{const next={...r};delete next[key];return next})}}/><small>{answer.trim()?answer.trim().split(/\s+/).length:0} words · {answer.length}/20,000 characters</small>
 <div className="coach-actions"><button className="primary" disabled={answer.trim().length<10||evaluating} onClick={evaluate}>{evaluating?<><Loader2 className="spin" size={15}/> Reviewing…</>:'Get feedback'}</button><button className="outline" disabled={index===0||evaluating} onClick={()=>setActive(visible[index-1].id)}>Previous</button><button className="outline" disabled={index===visible.length-1||evaluating} onClick={()=>setActive(visible[index+1].id)}>Next question</button></div>
 {feedback&&<div className="feedback" role="status"><h3>{localAI?'Local AI feedback':'Keyword coverage'} <span>{feedback.score}/10</span></h3><p>{feedback.improved_answer_suggestion}</p>{feedback.strengths.map(s=><p key={s}>{s}</p>)}{!!feedback.missing_elements.length&&<><h4>Areas to strengthen</h4><ul>{feedback.missing_elements.map(m=><li key={m}>{m}</li>)}</ul></>}</div>}
 <p className="muted">{current.provenance}</p>{current.sources.map(s=><p className="interview-source" key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><small>{s.status}</small></p>)}
 </>:<div className="empty"><h3>No questions match these filters.</h3><p>Clear your filters or select the full question library.</p><button className="outline" onClick={()=>{setSearch('');setRole('');setStage('');setCategory('')}}>Clear filters</button></div>}</section></div>
 <section className="interview-library"><h2>Question library</h2><p>{visible.length} matching questions · {Object.keys(drafts).filter(k=>k.startsWith(`${job||'library'}:`)&&drafts[k].trim()).length} answers drafted in this view</p><div className="interview-question-list">{!loading&&visible.map(q=><button disabled={evaluating} className={q.id===current?.id?'active':''} key={q.id} onClick={()=>setActive(q.id)}><span>{q.category} · {q.role_families.join(', ')}</span><strong>{q.question}</strong><small>{drafts[`${job||'library'}:${q.id}`]?.trim()?'Answer drafted':'Ready to practice'}</small></button>)}</div></section>
 <details className="interview-guidance"><summary>Research sources & coverage</summary><p>References informed topic coverage. Community reports are anecdotal. Technical scenarios are original editorial exercises. No employer-specific frequency or verification is claimed.</p>{catalog?.sources.map(s=><p className="interview-source" key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><small>{s.status}</small></p>)}</details></div>
}
