'use client';
export default function JobSignals({job,compact=false}:{job:any;compact?:boolean}){
 const posted=job.posted_at?new Date(job.posted_at):null;
 const valid=posted&&!Number.isNaN(posted.getTime());
 const date=valid?(job.posted_at_precision==='date'?posted!.toLocaleDateString():posted!.toLocaleString()):'Posting date not supplied';
 const visa=({explicit_yes:'Sponsorship mentioned',explicit_no:'No sponsorship / existing work rights required',likely:'Possible sponsorship · unconfirmed',unknown:'Sponsorship unknown'} as any)[job.visa_status||'unknown'];
 if(compact)return <small className="job-freshness">{valid?`Posted ${date}`:'Posting date unknown'}</small>;
 return <section className="job-signals"><h3>Source, freshness & eligibility</h3><p><strong>{job.source||'Manual import'}</strong> · {date}{job.application_priority?.age_days!=null&&` · ${Math.floor(job.application_priority.age_days)} days old`}</p>{job.application_priority&&<p>Application priority: <strong>{job.application_priority.score}/100 · {job.application_priority.decision.replaceAll('_',' ')}</strong><small>{job.application_priority.method}</small></p>}<p>{visa}</p>{job.visa_evidence?.map((s:string,i:number)=><blockquote key={i}>{s}</blockquote>)}<small>{job.visa_note||'A sponsored job advertisement is not evidence of visa sponsorship.'}</small>{job.application_priority?.language_eligibility?.missing?.length>0&&<p className="error-banner">Required language not met: {job.application_priority.language_eligibility.missing.join(', ')}</p>}{job.application_priority?.language_eligibility?.unknown?.length>0&&<p>Confirm language proficiency: {job.application_priority.language_eligibility.unknown.join(', ')}</p>}{job.first_seen_at&&<small>First seen by Job Hunter: {new Date(job.first_seen_at).toLocaleString()}. This is not the posting date.</small>}{job.alternative_sources?.length>0&&<details><summary>Other sources for this opening</summary>{job.alternative_sources.map((s:any)=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.source} ↗</a></p>)}</details>}</section>
}
