'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
export default function ModelLab(){
 const [routing,setRouting]=useState<any>(null);
 useEffect(()=>{api('/career/model-routing').then(setRouting).catch(()=>{})},[]);
 const [data,setData]=useState<any>(null),[chosen,setChosen]=useState<string[]>([]),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/models').then(d=>{setData(d);setChosen(d.models.map((m:any)=>m.name).slice(0,4))}).catch(e=>setError(e.message));const load=()=>api('/models/comparison').then(setResult).catch(e=>setError(e.message));load();const t=setInterval(load,4000);return()=>clearInterval(t)},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Model action failed')}finally{setBusy(false)}}
 return <section className="studio-card"><h2>Local model lab</h2><p>Compare free-to-run local models before choosing one for AI-assisted tasks. Resumes use exact source facts and profile fit remains explainable rules.</p>{error&&<p className="error-banner" role="alert">{error}</p>}{data&&<><label>Active local model<select aria-label="Active local model" disabled={busy||result?.status==='running'} value={data.active} onChange={e=>run(async()=>{const r=await api('/models/active','POST',{name:e.target.value});setData({...data,active:r.active})})}>{data.models.map((m:any)=><option key={m.name} value={m.name}>{m.name} · {(m.size_bytes/1e9).toFixed(1)} GB</option>)}</select></label><p>{data.note}</p>{!data.enabled&&<p>Local AI is disabled. Enable it in your local setup before running benchmarks; template features remain available.</p>}{routing&&<details><summary>Task-specific model routing</summary><p>Small: extraction. Medium: evaluation and writing. Strong: strategy and bounded review. Embedding: an embedding model such as nomic-embed-text. A model's presence does not guarantee task compatibility.</p>{['small','medium','strong','embedding'].map(tier=><label key={tier}>{tier}<select aria-label={tier} value={routing.tiers[tier]||''} onChange={e=>setRouting({...routing,tiers:{...routing.tiers,[tier]:e.target.value}})}><option value={routing.tiers[tier]}>{routing.tiers[tier]}</option>{data.models.filter((m:any)=>m.name!==routing.tiers[tier]).map((m:any)=><option key={m.name} value={m.name}>{m.name}</option>)}</select></label>)}<button disabled={busy} className="outline" onClick={()=>run(async()=>{setRouting(await api('/career/model-routing','PUT',{model_tiers:routing.tiers}))})}>Save routing</button></details>}{data.models.map((m:any)=><label className="check-label" key={m.name}><input type="checkbox" checked={chosen.includes(m.name)} onChange={e=>setChosen(e.target.checked?[...chosen,m.name].slice(0,4):chosen.filter(x=>x!==m.name))}/>{m.name}</label>)}<button className="primary" disabled={busy||!data.enabled||!chosen.length||result?.status==='running'} onClick={()=>run(async()=>{await api('/models/compare','POST',{models:chosen});setResult({status:'running',results:[]})})}>{result?.status==='running'?'Comparing locally…':'Run evidence benchmark'}</button></>}{result&&<><p>{result.method||'Checks skill extraction, missing evidence and instruction resistance on three synthetic examples. It does not evaluate overall writing quality.'}</p>{result.results?.map((r:any)=><div className="source-report" key={r.model}><strong>{r.model} · {r.passed}/{r.total} correct · {r.seconds}s total</strong><details><summary>Inspect outputs</summary><pre>{JSON.stringify(r.cases,null,2)}</pre></details></div>)}{result.status==='running'&&<p role="status">Models run sequentially to fit local memory. Results appear after each model.</p>}</>}</section>
}
