'use client';
import {useEffect,useRef,useState} from 'react';
import {Upload,FileText,Download,Check,Loader2,X} from 'lucide-react';
import {api,BASE} from '@/lib/api';
export type Resume={resume_id:string;label:string;file_type:string;original_name:string;keywords:string[];created_at:string|null};
export default function ResumeLibrary(){
 const [items,setItems]=useState<Resume[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState<any>(null),[name,setName]=useState('');const input=useRef<HTMLInputElement>(null);
 async function refresh(){setItems(await api<Resume[]>('/resumes'))}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setError('');setMessage('');let count=0;const errors=[];for(const file of Array.from(files)){try{if(file.size>10*1024*1024)throw new Error('Maximum file size is 10 MB.');const form=new FormData();form.append('file',file);const r=await fetch(`${BASE}/api/v1/resumes/upload`,{method:'POST',body:form});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Upload failed.');count++;}catch(e){errors.push(`${file.name}: ${e instanceof Error?e.message:'Upload failed'}`)}}await refresh().catch(e=>errors.push(e.message));setMessage(count?`${count} resume file${count===1?'':'s'} processed and indexed locally.`:'');setError(errors.join(' '));setBusy(false);if(input.current)input.current.value=''}
 return <section className="resume-library"><div className="section-heading"><div><h2>Your resume library <span className="count">{items.length}</span></h2><p>Keep different versions for different roles. We’ll suggest the closest match before you prepare an application.</p></div><button className="primary" disabled={busy} onClick={()=>input.current?.click()}>{busy?<Loader2 size={15} className="spin"/>:<Upload size={15}/>} Upload resumes</button><input ref={input} aria-label="Upload resume files" className="visually-hidden" type="file" multiple accept=".pdf,.docx,.txt" onChange={e=>upload(e.target.files)}/></div><div className="upload-note">PDF, DOCX, or TXT · Up to 10 MB each · Multiple files supported · Text extraction and keyword indexing stay on your computer. Scanned PDFs need OCR first.</div>{message&&<p className="success-message" role="status"><Check size={14}/>{message}</p>}{error&&<p className="error-banner" role="alert">{error}</p>}<div className="resume-grid">{items.map(r=><article className="resume-card" key={r.resume_id}><div className="section-title"><FileText size={22}/><span className="small-label">{r.file_type.toUpperCase()}</span></div><h3>{r.label}</h3><small>{r.original_name}</small><div className="keyword-corpus">{r.keywords.slice(0,12).map(k=><span key={k}>{k}</span>)}{r.keywords.length>12&&<span>+{r.keywords.length-12} more</span>}</div><div className="detail-actions"><button className="outline compact" onClick={async()=>{try{const data=await api(`/resumes/${r.resume_id}`);setPreview(data);setName(data.label)}catch(e){setError(e instanceof Error?e.message:'Could not read resume')}}}>Review text & keywords</button>{r.resume_id!=='profile'&&<a className="text-link" href={`${BASE}/api/v1/resumes/${r.resume_id}/download`}><Download size={13}/> Original</a>}</div></article>)}</div>{!items.length&&<div className="empty"><FileText/><h3>Add your first resume.</h3><p>Upload several versions to compare their fit for each job.</p></div>}{preview&&<div className="resume-preview"><div className="section-title"><h3>Review extracted text</h3><button className="icon-button" aria-label="Close resume preview" onClick={()=>setPreview(null)}><X size={18}/></button></div>{preview.resume_id!=='profile'&&<form className="rename-resume" onSubmit={async e=>{e.preventDefault();try{await api(`/resumes/${preview.resume_id}`,'PATCH',{label:name});await refresh();setMessage('Resume renamed.')}catch(e){setError(e instanceof Error?e.message:'Could not rename resume')}}}><label>Resume label<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><button className="outline">Save label</button></form>}<h4>Keyword corpus · {preview.keywords.length} terms</h4><div className="keyword-corpus">{preview.keywords.map((k:string)=><span key={k}>{k}</span>)}</div><pre>{preview.text}</pre></div>}</section>
}
