'use client';
import {useEffect,useState} from 'react';
import {Sparkles,Loader2} from 'lucide-react';
import {api,Job} from '@/lib/api';
type Match={resume_id:string;label:string;score:number;matched_keywords:string[];missing_keywords:string[];limited_description:boolean};
export type MatchResponse={matches:Match[];selected_resume_id:string|null;recommended_resume_id:string|null;method:string};
export default function ResumeMatcher({job,onChanged}:{job:Job;onChanged:()=>void}){
 const [data,setData]=useState<MatchResponse|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{let live=true;setData(null);setError('');api<MatchResponse>(`/applications/${job.job_id}/resume-matches`).then(r=>{if(live)setData(r)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[job.job_id,job.status]);
 if(error)return <p className="error-banner">{error}</p>;
 if(!data)return <p className="muted">Comparing your resumes…</p>;
 const chosen=data.selected_resume_id||data.recommended_resume_id||'profile';const match=data.matches.find(r=>r.resume_id===chosen);const best=data.matches[0];const editable=['MATCHED','DISCOVERED','TAILORED'].includes(job.status);
 return <section className="resume-match-panel"><h3><Sparkles size={15}/> Best resume for this job</h3>{best&&<p>{best.score>0?<><strong>{best.label}</strong> · {best.score.toFixed(1)}% text similarity</>:'No meaningful keyword overlap. Review the job description and your resume.'}</p>}<label>Resume for manual application<select aria-label="Resume for manual application" disabled={!editable||saving} value={chosen} onChange={async e=>{setSaving(true);setError('');try{await api(`/applications/${job.job_id}/resume`,'POST',{resume_id:e.target.value});setData({...data,selected_resume_id:e.target.value});onChanged()}catch(err){setError(err instanceof Error?err.message:'Could not select resume')}finally{setSaving(false)}}}>{data.matches.map(r=><option value={r.resume_id} key={r.resume_id}>{r.label} · {r.score.toFixed(1)}%{r.resume_id===data.recommended_resume_id?' · Recommended':''}</option>)}</select></label>{match&&<><small>Shared keywords</small><div className="keyword-corpus">{match.matched_keywords.length?match.matched_keywords.map(k=><span key={k}>{k}</span>):<span>No shared keywords</span>}</div>{match.limited_description&&<p className="muted">The job description is short or incomplete. This recommendation has limited evidence.</p>}</>}<p className="muted">Compare these versions for manual applications. Template preparation uses verified facts from My profile; uploaded files are not rewritten automatically.</p></section>
}
export function PreparationReview({jobs,onPrepare}:{jobs:Job[];onPrepare:(selections:Record<string,string>)=>Promise<void>}){
 const [results,setResults]=useState<Record<string,MatchResponse>>({}),[selections,setSelections]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;Promise.all(jobs.map(async j=>[j.job_id,await api<MatchResponse>(`/applications/${j.job_id}/resume-matches`)] as const)).then(pairs=>{if(!live)return;setResults(Object.fromEntries(pairs));setSelections(Object.fromEntries(pairs.map(([id,r])=>[id,'profile'])))}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[jobs.map(j=>j.job_id).join(',')]);
 const loaded=jobs.every(j=>results[j.job_id]);
 return <><h2>Prepare from verified facts.</h2><p>The fixed one-page template uses My profile. If an upload has better evidence, add and verify its achievements in Application Studio first. Your original files remain available for manual applications. No applications are sent at this step.</p>{error&&<p className="error-banner" role="alert">{error}</p>}{!loaded&&!error&&<p className="muted">Building resume recommendations…</p>}{jobs.map(j=>{const result=results[j.job_id];return <div className="preparation-job" key={j.job_id}><strong>{j.company_name} · {j.job_title}</strong>{result&&<><p className="muted">Closest text match: {result.matches.find(r=>r.resume_id===result.recommended_resume_id)?.label||'No clear match'}. Preparation source: My profile.</p><label>Resume for {j.company_name}<select value={selections[j.job_id]} onChange={e=>setSelections({...selections,[j.job_id]:e.target.value})}>{result.matches.filter(r=>r.resume_id==='profile').map(r=><option value={r.resume_id} key={r.resume_id}>{r.label} · {r.score.toFixed(1)}%{r.resume_id===result.recommended_resume_id?' · Recommended':''}</option>)}</select></label><div className="keyword-corpus">{result.matches.find(r=>r.resume_id===selections[j.job_id])?.matched_keywords.slice(0,8).map(k=><span key={k}>{k}</span>)}</div>{!result.recommended_resume_id&&<small>No strong overlap found; choose a resume manually.</small>}</>}</div>})}<button className="primary full" disabled={!loaded||busy||!!error} onClick={async()=>{setBusy(true);try{await onPrepare(selections)}catch(e){setError(e instanceof Error?e.message:'Preparation failed')}finally{setBusy(false)}}}>{busy?<Loader2 size={15} className="spin"/>:<Sparkles size={15}/>} Prepare {jobs.length} application{jobs.length===1?'':'s'}</button></>
}
