'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
export default function SkillTrends({version,onOpen}:{version:string;onOpen:(id:string)=>void}){
 const [role,setRole]=useState(''),[days,setDays]=useState('30'),[data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;setData(null);setError('');api(`/jobs/skill-trends?role=${encodeURIComponent(role)}&days=${days}`).then(value=>{if(active)setData(value)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[role,days,version]);
 return <section className="skill-trends"><div className="section-heading"><div><h2>Skills in demand</h2><p>What employers mention in your saved jobs. Select a role family to compare similar openings.</p></div><div className="table-controls"><select aria-label="Skills role family" value={role} onChange={e=>setRole(e.target.value)}><option value="">All role families</option>{Array.from(new Set([role,...(data?.roles||[])])).filter(Boolean).map((r:any)=><option key={r} value={r}>{r}</option>)}</select><select aria-label="Skills posting age" value={days} onChange={e=>setDays(e.target.value)}><option value="7">Past 7 days</option><option value="30">Past 30 days</option><option value="90">Past 90 days</option><option value="0">All saved dates</option></select></div></div>
 {error?<p role="alert">{error}</p>:!data?<p role="status">Analysing saved listings…</p>:<><p>{data.sample_size} unique postings · {data.with_description} with descriptions. {days!=='0'&&`${data.unknown_dates} postings without dates excluded.`}</p><small>Frequency in your saved sample, not a market-wide survey or proof of growth over time. Demo and deleted jobs are excluded; each posting counts once per skill. {data.sample_size<10&&'Small sample: search for more similar jobs before drawing conclusions.'}</small><div className="skill-trend-grid">{data.skills.map((s:any)=><details key={s.skill}><summary><strong>{s.skill}</strong><span>{s.count} / {data.sample_size} jobs · {s.percent}%</span><progress max="100" value={s.percent} aria-label={`${s.skill}: ${s.percent}%`}/></summary>{s.evidence.map((e:any)=><div className="skill-proof" key={e.job_id}><button className="text-link" onClick={()=>onOpen(e.job_id)}>{e.title} · {e.company}</button><small>{e.source}{e.posted_at?` · ${new Date(e.posted_at).toLocaleDateString()}`:''}</small><blockquote>{e.quote}</blockquote></div>)}</details>)}</div>{!data.skills.length&&<p>No skill mentions found for these filters. Expand the date range or search for more openings.</p>}</>}
 </section>
}
