"""Exercise the installed model using fictitious job/answer data only."""
import json
from pathlib import Path
from backend.main import app
from backend import database as db
from backend.agents.coach_agent import questions, feedback
from backend.agents.tailor_agent import tailor
from backend.demo import PROFILE, jobs

job=dict(jobs()[0],job_id='local-ai-verification',user_id='local')
qs=questions(job)
assert len(qs)==3,qs
assert all(q['question'] and q['evaluation_criteria'] for q in qs)
print('PASS: three interview questions generated by local model',flush=True)
result=feedback(qs[0],'At Example Studio, my goal was to speed up a React application. I profiled rendering, fixed unnecessary re-renders, and reduced page load time by 35%. I verified the result with before-and-after performance measurements.')
assert 0<=result['score']<=10
print('PASS: structured local AI feedback, score='+str(result['score']),flush=True)
resume,cover=tailor(job,PROFILE)
assert Path(resume).read_bytes().startswith(b'%PDF')
source=Path(resume).with_name('resume.json').read_text()
assert 'Reduced page load time by 35%' in source
print('PASS: Fact-grounded one-page resume PDF generated',flush=True)
(Path('data/runtime')/'ai-verification.json').write_text(json.dumps({'questions':qs,'feedback':result,'resume':resume},indent=2))
